### ISSUE TITLE
Posts not importing

### ISSUE THREAD

**Issue by chrisdrackett** [jonthornton/wp2tumblr#17]
So I'm trying to import some posts and I get a message that "147 posts have been imported!" but nothing is actually showing up on tumblr. Any thoughts? I've tried both on your service and locally on my machine.

**Comment by chrisdrackett** [comment]
nevermind, seems I hit the post limit for tumblr. Maybe add an error in that case?

**Comment by knarfytrebil** [comment]
Same Issue here.

**Comment by tc** [comment]
Make sure you change debug in the settings file to False
